version: '3'
networks:
  django-network:
    driver: bridge
volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data     
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}        
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - django-network

  backend:
    image: absurdnik/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    networks:
      - django-network

  frontend:
    image: absurdnik/foodgram_frontend
    command: cp -r build result_build
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend
    networks:
      - django-network
 
 